name: Test smbprotocol
on:
  push:
    branches:
    - master
    paths-ignore:
    - CHANGELOG.md
    - LICENSE
    - README.md

  pull_request:
    branches:
    - master
    paths-ignore:
    - CHANGELOG.md
    - LICENSE
    - README.md

  release:
    types:
    - published

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Build smbprotocol
      run: |
        python -m pip install build
        python -m build

    - name: Upload built smbprotocol
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: ./dist/*

  test:
    name: test
    needs:
    - build
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-2019
        - windows-2022
        python-version:
        - 3.8
        - 3.9
        - '3.10'
        - '3.11'
        - '3.12'
        python-arch:
        - x86
        - x64

        exclude:
        - os: ubuntu-latest
          python-arch: x86
        - os: macOS-latest
          python-arch: x86
        - os: windows-2019
          python-arch: x86
        - os: windows-2019
          python-version: 3.8
        - os: windows-2019
          python-version: 3.9
        - os: windows-2019
          python-version: '3.10'
        - os: windows-2019
          python-version: '3.12'

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.python-arch }}

    - uses: actions/download-artifact@v4
      with:
        name: artifact
        path: ./dist

    - name: Extract OS name
      shell: bash
      run: |
        NAME=$( echo '${{ matrix.os }}' | tr '-' ' ' | awk '{print $1}' )
        echo "${NAME}"
        echo "name=${NAME}" >> "${GITHUB_OUTPUT}"
      id: os

    - name: Test
      shell: bash
      run: |
        if [ "$(expr substr $(uname -s) 1 5)" == "MINGW" ]; then
            build_helpers/run-ci.sh
        else
            sudo -E build_helpers/run-ci.sh
        fi
      env:
        PYTEST_ADDOPTS: --color=yes

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Unit Test Results (${{ matrix.os }} ${{ matrix.python-version }} ${{ matrix.python-arch }})
        path: ./junit/test-results.xml

    - name: Upload Coverage Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Coverage Results (${{ matrix.os }} ${{ matrix.python-version }} ${{ matrix.python-arch }})
        path: ./coverage.xml

    - name: Upload Coverage to codecov
      if: always()
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.xml
        flags: ${{ steps.os.outputs.name }},py${{ matrix.python-version }},${{ matrix.python-arch }}
        token: ${{ secrets.CODECOV_TOKEN }}

  publish:
    name: publish
    needs:
    - test
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: artifact
        path: ./dist

    - name: Publish
      if: startsWith(github.ref, 'refs/tags/v')
      uses: pypa/gh-action-pypi-publish@release/v1
